### ISSUE TITLE
"content" with escapes in pseudo-element does not render correctly

### ISSUE THREAD

**Issue by mmastrac** [radkovo/CSSBox#11]
Not sure if this is a bug in CSSBox or jStyleParser. If a pseudoelement uses CSS unicode escapes in a content declaration, the escapes are written verbatim to the output. This is a problem that specifically affects the fontawesome stylesheet.

Repro:

    <style>
    .foo::before {
        content: "\0040";
    }
    </style>
    <span class="foo">yo</span>

Expected:

    "@yo"

Actual:

    "\0040yo"

**Comment by radkovo** [comment]
Hi, this issue should have been fixed some months ago and I am not able to reproduce the problem with the current release. What CSSBox and jStyleParser versions are you using? Could you provide more details about your software configuration? Thanks!

**Comment by mmastrac** [comment]
Using deps from maven inherited from swingbox-1.1.jar. I can probably override the dep with a newer version:

 * jstyleparser-1.18.jar
 * cssbox-4.7.jar
 * swingbox-1.1.jar

**Comment by mmastrac** [comment]
OK, confirmed that forcing Maven to use cssbox-4.8 fixes the issue. I'll close it.

**Comment by radkovo** [comment]
Thanks for pointing this out. I will check and fix the SwingBox dependencies.
