### ISSUE TITLE
data: url

### ISSUE THREAD

**Issue by LoriGolden** [radkovo/CSSBox#17]
Hi,

I'm wondering why the data: url is excluded from ImageRenderer.  It seems to work okay for html to png conversions.

from renderURL:

        if (!urlstring.startsWith("http:") &&
            !urlstring.startsWith("ftp:") &&
            !urlstring.startsWith("file:"))
                urlstring = "http://" + urlstring;
        

http://www.phpied.com/data-urls-what-are-they-and-how-to-use/

Regards,

Lori

**Comment by kryptt** [comment]
I think I am running into this issue myself..

**Comment by radkovo** [comment]
I couldn't imagine the impact of this. Are you using ImageRenderer as a command line tool and passing some data:urls through the command line? Actually, ImageRenderer was meant as a simple demo but I can add the data:url support if it helps.

**Comment by kryptt** [comment]
Is ImageRenderer used internally for rendering an <img src="data:image/png;base64,....." /> tag ?

**Comment by radkovo** [comment]
No, it's not. However, there has been related to the data URL decoding in the last release so if you are not using the latest CSSBox, I recommend to upgrade. If the problem persists, just let me know the details (ideally some testing case for which the decoding fails).

**Comment by kryptt** [comment]
The following html file renders correctly in a browser, but cssbox just renders a white background
https://www.dropbox.com/s/yrpg3wn839kblov/test.html?dl=1

**Comment by radkovo** [comment]
I have made some tests and I can confirm the image does not display in 4.9 but displays correctly with 4.10 (tested with all the provided demos, e.g. BoxBrowser). I just downloaded the 4.10 distribution package and run the demos in doc/examples. Can you check your classpath if 4.10 is really used?

**Comment by kryptt** [comment]
Yes, you're right, apparently I had a custom build somewhere because the sha1 didn't match. I deleted my version and after th re-download it worked! thanks for taking the time to review it! :+1:
