### ISSUE TITLE
ImageRenderer doesn't support https:// urls 

### ISSUE THREAD

**Issue by mplushnikov** [radkovo/CSSBox#23]
ImageRenderer doesn't support "https://" urls, because of wrong url rewriting: 
```java
if (!urlstring.startsWith("http:") &&
            !urlstring.startsWith("ftp:") &&
            !urlstring.startsWith("file:"))
                urlstring = "http://" + urlstring;
```
This code converts https://www.somedomain.com into http://https://www.somedomain.com

**Comment by radkovo** [comment]
Ok, added https. However, ImageRenderer is just a simple demo. You may experience other problems with https because the certificates are not solved at all and the built-in Java http client is quite basic.
