### ISSUE TITLE
Warnings being issued by CSSBox

### ISSUE THREAD

**Issue by abhsrivastava** [radkovo/CSSBox#33]
I am using CSSBox but I am seeing the warnings in my log which are originating out of CSSBox

msg: Unable to find method for property azimuth
msg: Unable to find method for property cue-after
msg: Unable to find method for property cue-after
msg: Unable to find method for property page-break.
category: cz.vutbr.web.domassign.DeclarationTransformer

I searched my codebase for the class DeclarationTransformer. I found that my code uses CSSBox and CSSBox uses DeclrationTransformer.

Can you please let me know how can I stop these warnings because they are flooding my logs.

**Comment by abhsrivastava** [comment]
I am also seeing a lot of messages with INFO level logged by the logger cz.vutbr.web.csskit.antlr.SimplePreparator

**Comment by radkovo** [comment]
Actually, the logs are produced by the jStyleParser library, not CSSBox. Already discussed [here](https://github.com/radkovo/jStyleParser/issues/66). Generally, this is not an issue to report as you should be able to configure logging in your application yourself.
