### ISSUE TITLE
Width and Padding

### ISSUE THREAD

**Issue by d1231** [radkovo/CSSBox#34]
Hi,

I think I found issue in the calculations of boxs width.

In BlockBox.java line 2037, you get the content width:
`content.width = dec.getLength(width, auto, 0, 0, contw);`

That value includes the padding, so when using totalWidth in ElementBox.java line 814:
`
    public int totalWidth()
    {
        return emargin.left + border.left + padding.left + content.width +
            padding.right + border.right + emargin.right;
    }
`

So the padding is calculated twice.

**Comment by radkovo** [comment]
To my best knowledge, content width [should not include padding](https://www.w3.org/TR/CSS22/box.html#box-dimensions) by default as long as you don't play with `box-sizing` which is unfortunately not supported by CSSBox yet. The code you mentioned has been tested quite well on many examples so I believe it's correct. However, if you have some example that demonstrates an error in CSSBox, I would be grateful if you could attach it.

**Comment by d1231** [comment]
You're correct about the box-sizing. 

The example I worked was similar to this one: https://jsfiddle.net/d1231/eoc1dprq/

Any timeline regarding the box-sizing feature?
Would you require any help?

Thanks

**Comment by radkovo** [comment]
I have added some experimental support for `box-sizing` to the master branch. It requires the git version of `jStyleParser` as well. For the first look it works but a thorough testing is necessary.

**Comment by d1231** [comment]
Thanks. I will check it in the coming days
