### ISSUE TITLE
4.13 version margins looks bad on simple template

### ISSUE THREAD

**Issue by Dedrakot** [radkovo/CSSBox#39]
For example this will looks ok in 4.12:
<pre>&lt;!DOCTYPE html&gt;
&lt;html lang=&quot;en&quot;&gt;
  &lt;body&gt;
    &lt;div&gt;
      &lt;img src=&quot;{Some image url}&quot;/&gt;
    &lt;/div&gt;
  &lt;/body&gt;
&lt;/html&gt;</pre>
But on 4.13 we get black margins on the right, botom and a little bit on the top and left.

**Comment by radkovo** [comment]
I made some changes in the background color related code but I am not able to reproduce this issue with the HTML code provided. Could you provide a link to a real document where the issue appears? Thanks!

**Comment by Dedrakot** [comment]
Let's use google icon as img tag source: https://www.google.ru/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png
And part of code from ImageRenderer demo:
<pre>
try(DocumentSource docSource = new StreamDocumentSource(is, base, "text/html;charset=utf-8")) {

    //Parse the input document
    DOMSource parser = new DefaultDOMSource(docSource);
    Document doc = parser.parse();

    //create the media specification
    MediaSpec media = new MediaSpec("screen");
    media.setDimensions(size.width, size.height);
    media.setDeviceDimensions(size.width, size.height);

    //Create the CSS analyzer
    DOMAnalyzer da = new DOMAnalyzer(doc, base);
    da.setMediaSpec(media);
    da.attributesToStyles(); //convert the HTML presentation attributes to inline styles
    da.addStyleSheet(null, CSSNorm.stdStyleSheet(), DOMAnalyzer.Origin.AGENT); //use the standard style sheet
    da.addStyleSheet(null, CSSNorm.userStyleSheet(), DOMAnalyzer.Origin.AGENT); //use the additional style sheet
    da.addStyleSheet(null, CSSNorm.formsStyleSheet(), DOMAnalyzer.Origin.AGENT); //render form fields using css
    da.getStyleSheets(); //load the author style sheets

    BrowserCanvas contentCanvas = new BrowserCanvas(da.getRoot(), da, base);
    contentCanvas.setAutoMediaUpdate(false); //we have a correct media specification, do not update
    contentCanvas.getConfig().setClipViewport(cropWindow);
    contentCanvas.getConfig().setLoadImages(loadImages);
    // increase timeout
    contentCanvas.getConfig().setImageLoadTimeout(5000);
    contentCanvas.getConfig().setLoadBackgroundImages(loadBackgroundImages);

    contentCanvas.createLayout(size);
    return contentCanvas.getImage();
}
</pre>
4.13:
![image](https://user-images.githubusercontent.com/13083659/30276448-916dea4c-970d-11e7-9c76-09f59e22cea7.png)
4.12:
![image](https://user-images.githubusercontent.com/13083659/30276644-2da4eaf0-970e-11e7-99ed-4d7bba618462.png)
May be it depends on transparent color. When I use https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRzjKfOiVevEd9AzB2VwUT2oEkVlze5n451EKA5YcphNTPA5PjswA:
![image](https://user-images.githubusercontent.com/13083659/30277028-49f0f1b2-970f-11e7-9836-6b7f3e6069c0.png)

**Comment by Dedrakot** [comment]
I check out revision bec549040624bb000c2fcfa36b915482836d0133 (Clear viewport background). And it works fine. Thanks. The bad thing it isn`t working on release.
