### ISSUE TITLE
Register custom fonts from font-face rules with AWT

### ISSUE THREAD

**Issue by czaurel** [radkovo/CSSBox#42]
AFAIK, the `@font-face` rules are only parsed but not used for actually doing anything with the font files. A basic implementation, which uses the `font-family` and `src` parts to call `GraphicsEnvironment.registerFont` could be pretty useful for using custom TTFs.

**Comment by czaurel** [comment]
For the RuleFontFace properties, see https://github.com/radkovo/jStyleParser/issues/78.

**Comment by radkovo** [comment]
It seems that font face rules are more complex. Mainly, there may be multiple sources (including local fonts etc.) I have reworked your implementation to correspond to the specification and I have moved the AWT-related part to VisualContext (to make things consistent). See the last few commits in both CSSBox and jStyleParser.
