### ISSUE TITLE
word-break: break-all;  Unavailable？

### ISSUE THREAD

**Issue by 9745155535** [radkovo/CSSBox#48]
word-wrap

**Comment by danielbmesquita** [comment]
word-wrap doesnt work too, inside a table at least.

**Comment by raudus** [comment]
https://www.facebook.com/RaudusExperts/videos/2530384250410587/?t=0

Em dom., 8 de mar. de 2020 às 12:51, danielbmesquita <
notifications@github.com> escreveu:
