### ISSUE TITLE
Nested tags (with inline styles) don't work for styles with text-decoration

### ISSUE THREAD

**Issue by tr-mm** [radkovo/CSSBox#56]
It seems that  having nested (nonblock)tags (like "span") with inline style information, where the outer block has a "text-decoration: underline" for example, and an inner block having any other style like "font-weight: bold", the inner block overwrites the outer blocks text-decoration style with "text-decoration: none"

For Example (does not work): 
`<div class="whatever"><span style="text-decoration: underline;">AAA<span style="font-weight: bold;">TEST TEST TEST</span></span></div>`
Here only the first word is underlined, the TEST words are only bold

`<div class="whatever"><span style="text-decoration: underline;"><span style="font-weight: bold;">TEST TEST TEST</span></span></div>`
Here the TEST words are only bold

but this works:
`<div class="whatever"><span style="font-weight: bold;">AAA<span style="text-decoration: underline;">TEST TEST TEST</span></span></div>`
Here ALL words are bold, and the TEST words are also underlined

`<div class="whatever"><span style="font-weight: bold;"><span style="text-decoration: underline;">TEST TEST TEST</span></span></div>`
Here ALL words are bold and underlined

I'd also like to mention that this happens when the styles are defined via short/old notation:
WRONG RESULT:  `<div class="whatever"><u>AAA<b>TEST TEST TEST</b></u></div>`
WRONG RESULT:  `<div class="whatever"><u><b>TEST TEST TEST</b></u></div>`
CORRECT RESULT: `<div class="whatever"><b>AAA<u>TEST TEST TEST</u></b></div>`
CORRECT RESULT: `<div class="whatever"><b><u>TEST TEST TEST</u></b></div>`

**Comment by radkovo** [comment]
Thanks for pointing this out. You're right, the text decorations were not correctly propagated to child elements. A fix is available now; thorough testing is required.
