### ISSUE TITLE
InlineBox vs. Blockbox in 4.17 -> no more rendering possible

### ISSUE THREAD

**Issue by tr-mm** [radkovo/CSSBox#57]
Version 4.17 can no longer render any of our html parts, whereas Version 4.16 rendered everything.

This might be an older issue that went into the code again, - seems quite similar to #47 

org.fit.cssbox.layout.InlineBox cannot be cast to org.fit.cssbox.layout.BlockBox: java.lang.ClassCastException: org.fit.cssbox.layout.InlineBox cannot be cast to org.fit.cssbox.layout.BlockBox
at org.fit.cssbox.layout.BlockBox.computeEfficientMargins(BlockBox.java:756) [cssbox-4.17.jar:]
at org.fit.cssbox.layout.ElementBox.initSubtree(ElementBox.java:295) [cssbox-4.17.jar:]
at org.fit.cssbox.layout.Viewport.initSubtree(Viewport.java:145) [cssbox-4.17.jar:]

**Comment by radkovo** [comment]
Could you please provide an example of a simple input document that leads to this error?

**Comment by tr-mm** [comment]
Here is an example document:


[example.zip](https://github.com/radkovo/CSSBox/files/3858935/example.zip)

**Comment by radkovo** [comment]
The example code seems to render normally using the provided demos such as [ImageRenderer](https://github.com/radkovo/CSSBox/blob/master/src/main/java/org/fit/cssbox/demo/ImageRenderer.java). Generally, the problem occurs when the root element (`html`) is not block. This may be caused by not using the built-in style sheets (like [here](https://github.com/radkovo/CSSBox/blob/master/src/main/java/org/fit/cssbox/demo/ImageRenderer.java#L118)). Does it help when you add `html { display: block; }` to the style?

**Comment by tr-mm** [comment]
it is strange. If we add the display:block to the html element, then it gets rendered without an error, but the html is rendered as a text, not as an html page.

The Code we use to render is nearly identical to the ImageRenderer Demo, we also used the built-instyle sheets:

` DOMParser parser;
                parser = new DOMParser();

                parser.setProperty("http://cyberneko.org/html/properties/names/elems", "lower");
                parser.setProperty("http://cyberneko.org/html/properties/default-encoding", StandardCharsets.UTF_8);
                parser.parse(new InputSource(new StringReader(text)));
                Document doc = parser.getDocument();
                MediaSpec media = new MediaSpec("screen");
                media.setDimensions(d.width, d.height);
                media.setDeviceDimensions(d.width, d.height);

       
                DOMAnalyzer da = new DOMAnalyzer(doc);
                da.setMediaSpec(media);
                da.attributesToStyles();
                da.addStyleSheet(null, CSSNorm.stdStyleSheet(), DOMAnalyzer.Origin.AGENT); 
                da.addStyleSheet(null, CSSNorm.userStyleSheet(), DOMAnalyzer.Origin.AGENT);
                da.addStyleSheet(null, CSSNorm.formsStyleSheet(), DOMAnalyzer.Origin.AGENT); 
                da.getStyleSheets(); //load the author style sheets

                BrowserCanvas contentCanvas = new BrowserCanvas(da.getRoot(), da, baseUrl);
                contentCanvas.setAutoMediaUpdate(false);
                contentCanvas.getConfig().setClipViewport(true);
                contentCanvas.getConfig().setLoadImages(false);
                contentCanvas.getConfig().setLoadBackgroundImages(false);
                contentCanvas.createLayout(d);

                BufferedImage bi = contentCanvas.getImage();`

**Comment by radkovo** [comment]
We're getting closer. In 4.17, the built-in style sheets have moved to separate resources in classpath (in [src/main/resources](https://github.com/radkovo/CSSBox/tree/master/src/main/resources/css)) and it seems that the resources are not correctly loaded [here](https://github.com/radkovo/CSSBox/tree/master/src/main/resources/css). I am trying to imagine why. Is your code part of a standalone java application or is it running in a container (e.g. Tomcat web container)?

**Comment by tr-mm** [comment]
It's part of a bigger application running in an container under Wildfly

**Comment by radkovo** [comment]
Ok, that could explain why I didn't experience the bug in a standalone app. Hopefully, [this commit](https://github.com/radkovo/CSSBox/commit/c1517f9e1755cca4bb8a9e5da2d644019113e2e9) should fix the bug. Are you able to test it?

**Comment by tr-mm** [comment]
Just tested it, Yes, this change seems to fix the bug.

**Comment by radkovo** [comment]
Great news, thanks for testing. I will include the fix in the next release.
