### ISSUE TITLE
no fontmanager in java.library.path

### ISSUE THREAD

**Issue by mazhifu-fit2cloud** [radkovo/CSSBox#59]
err info : Handler dispatch failed; nested exception is java.lang.UnsatisfiedLinkError: no fontmanager in java.library.path

im run cssbox centos has this info, but i run in the mac os hasn't this problem, this why?

**Comment by radkovo** [comment]
This seems to me like a problem with your Java runtime environment (JRE) installation. Some hints may be found here:
https://stackoverflow.com/questions/37251309/no-fontmanager-in-java-library-path/39861372

**Comment by mazhifu-fit2cloud** [comment]
this problem is linux os need to install fontconfig.
talk about how to i solved,  my project running in docker ,  just started i instsalled in my host fontconfig, so is not effective; my project running in the docker container,   add the dockerfile :
`RUN add --update openjdk8-jre fontconfig ttf-dejavu`
and later , has another error is garbled, because is chinese problem , so i must add chinese font in 
 the dockerfile . 
it's ok
